apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
spec:
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
      - name: mlflow
        image: jhginn/mlflow:latest
        command: ["mlflow"]
        args: [
          "server", 
          "--host", "0.0.0.0", 
          "--port", "5001", 
          "--default-artifact-root", "./mlruns",
          "--backend-store-uri", {{ .Values.backendDatabase }}
        ]
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        # resources:
        #   limits:
        #     memory: "500Mi"
        #     cpu: "500m"
        ports:
        - containerPort: 5001
      restartPolicy: Always
