apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
spec:
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
      - name: mlflow
        image: jhginn/mlflow:latest
        command: ["mlflow"]
        args: [
          "server", 
          "--host", "0.0.0.0", 
          "--port", "5000", 
          "--default-artifact-root", "./mlruns"
        ]
        #"--backend-store-uri", 
        #"postgresql+psycopg2://postgres:password@postgres.postgres.svc.cluster.local/postgres",
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        # resources:
        #   limits:
        #     memory: "500Mi"
        #     cpu: "500m"
        ports:
        - containerPort: 5000
      restartPolicy: Always
